### ISSUE TITLE
Would love an answer key

### ISSUE THREAD

**Issue by matthova** [frenchroasted/RegexKoans#4]
Really stumped on one of the questions. Also wondering if I've actually done what is considered "best practice" on some of the other questions. Given that many of the questions have multiple acceptable answers, an answer key (separate from the koan files) would be a great resource.

**Comment by frenchroasted** [comment]
I know this is a long time coming, but I finally got around to filling out all the test specs and adding the answer key to the repository. See the "answers" directory for solutions to the questions. Remember, many of the questions have multiple possible solutions. The more complicated the regex, the more ways there are to solve it. So this answer key is just one way to answer the questions.

One other note: There are a few cases where the regular expressions use what look like excessive capture groups. For example:
```
/((\.[\d])?)/
```
The outermost ( ) looks unnecessary, but it's written that way because the test assertion is comparing the capture group to a string value. If the outer ( ) is missing, then javascript will fill out that capture group with either a string or undefined, depending on whether it's there or not. This is difficult to check in a test assertion. Wrapping the whole thing in another capture group means the final value will always be a string - either an empty string or a string full of stuff from the match. Then it's much easier to say "expect().toEqual('')".

In real life, would you use the extra group? It depends on what you're doing with the data. If you just want to check if the string matches the regex, you don't need the extra group. If you want to capture that particular piece of the string, you might want the extra capture group for the same reason I did in the test script: It makes the rest of the code more convenient.
